package com.zyhao.openec.order.entity;

import java.io.Serializable;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.validation.constraints.Min;

/**
 * Model class of 库存表.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Entity
public class Inventory implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** sku. */
	@Id
	private String sku;

	/** 商品编码. */
	private String code;

	/** 商品条形码. */
	private String barCode;

	/** 售价格. */
	@Min(0)
	private Integer price;

	/** 数量. */
	@Min(0)
	private Integer amount;

	/** 规格JSON. */
	private String specs;

	/** 图片JSON. */
	private String pictures;

	/**
	 * Constructor.
	 */
	public Inventory() {
	}

	/**
	 * Set the sku.
	 * 
	 * @param sku
	 *            sku
	 */
	public void setSku(String sku) {
		this.sku = sku;
	}

	/**
	 * Get the sku.
	 * 
	 * @return sku
	 */
	public String getSku() {
		return this.sku;
	}

	/**
	 * Set the 商品编码.
	 * 
	 * @param code
	 *            商品编码
	 */
	public void setCode(String code) {
		this.code = code;
	}

	/**
	 * Get the 商品编码.
	 * 
	 * @return 商品编码
	 */
	public String getCode() {
		return this.code;
	}

	/**
	 * Set the 商品条形码.
	 * 
	 * @param barCode
	 *            商品条形码
	 */
	public void setBarCode(String barCode) {
		this.barCode = barCode;
	}

	/**
	 * Get the 商品条形码.
	 * 
	 * @return 商品条形码
	 */
	public String getBarCode() {
		return this.barCode;
	}

	/**
	 * Set the 售价格.
	 * 
	 * @param price
	 *            售价格
	 */
	public void setPrice(Integer price) {
		this.price = price;
	}

	/**
	 * Get the 售价格.
	 * 
	 * @return 售价格
	 */
	public Integer getPrice() {
		return this.price;
	}

	/**
	 * Set the 数量.
	 * 
	 * @param amount
	 *            数量
	 */
	public void setAmount(Integer amount) {
		this.amount = amount;
	}

	/**
	 * Get the 数量.
	 * 
	 * @return 数量
	 */
	public Integer getAmount() {
		return this.amount;
	}

	/**
	 * Set the 规格JSON.
	 * 
	 * @param specs
	 *            规格JSON
	 */
	public void setSpecs(String specs) {
		this.specs = specs;
	}

	/**
	 * Get the 规格JSON.
	 * 
	 * @return 规格JSON
	 */
	public String getSpecs() {
		return this.specs;
	}

	/**
	 * Set the 图片JSON.
	 * 
	 * @param pictures
	 *            图片JSON
	 */
	public void setPictures(String pictures) {
		this.pictures = pictures;
	}

	/**
	 * Get the 图片JSON.
	 * 
	 * @return 图片JSON
	 */
	public String getPictures() {
		return this.pictures;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((sku == null) ? 0 : sku.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Inventory other = (Inventory) obj;
		if (sku == null) {
			if (other.sku != null) {
				return false;
			}
		} else if (!sku.equals(other.sku)) {
			return false;
		}
		return true;
	}

}
