package com.zyhao.openec.order.entity;
import java.io.Serializable;

import javax.persistence.Entity;
import javax.persistence.Id;

/**
 * Model class of 支付表.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */

@Entity(name="payinfo")
public class PayInfo implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 商户订单号. */
	@Id
	private String outTradeNo;

	/** 订单总金额(分). */
	private Integer totalPrice;

	/** 订单总运费(分). */
	private Integer totalFare;

	/** 实付金额(分). */
	private Integer payPrice;

	/** 使用总积分. */
	private Integer totalPoints;

	/** 提交时间. */
	private Long commitTime;

	/** 用户id. */
	private String userId;

	/** 渠道id. */
	private String channelId;

	/** 订单内容校验码(针对订单支付金额，随机数，支付方式，系统支付编码进行md5加密). */
	private String contentMd5;

	/** 支付方式:默认0-无 1-微信 2-支付宝 3-银联. */
	private String payWay;

	/** 支付类型. */
	private String payType;

	/** 支付状态（默认-0，成功-1，失败-2，3-异常）. */
	private String payStatus;

	/** 返回状态码. */
	private String returnCode;

	/** 返回信息. */
	private String returnMsg;

	/** 业务结果. */
	private String resultCode;

	/** 错误代码. */
	private String errCode;

	/** 错误代码描述. */
	private String errCodeDes;

	/** 商品名称. */
	private String subject;

	/** 商品描述. */
	private String body;

	/** 商品详情. */
	private String detail;

	/** 前台同步通知状态. */
	private String frontNotifyStatus;

	/** 卖家帐号（卖家在支付平台注册的号）. */
	private String sellerNum;

	/** 卖家帐户号（支付平台分配给卖家的号）. */
	private String sellerId;

	/** 买家账户号（支付平台分配给买家的身份标志）. */
	private String buyerId;

	/** 买家支付银行帐号. */
	private String bankNo;

	/** 设备号. */
	private String deviceInfo;

	/** 参数编码字符集. */
	private String charset;

	/** 签名方式. */
	private String signType;

	/** 签名. */
	private String sign;

	/** 附加数据. */
	private String attch;

	/** 交易类型. */
	private String tradeType;

	/** 交易状态. */
	private String tradeStatus;

	/** 预支付交易会话标识. */
	private String prepayId;

	/** 通知时间. */
	private Long notifyTime;

	/** 通知类型. */
	private String notifyType;

	/** 通知校验ID. */
	private String notifyId;

	/** 交易流水号. */
	private String tradeNo;

	/** 交易创建时间. */
	private Long gmtCreate;

	/** 交易付款时间. */
	private Long gmtPayment;

	/** 交易关闭时间. */
	private Long gmtClose;

	/** 扩展字段. */
	private String ext;

	
	private String businessId;
	/**
	 * Constructor.
	 */
	public PayInfo() {
	}

//	/**
//	 * Set the 主键.
//	 * 
//	 * @param id
//	 *            主键
//	 */
//	public void setId(String id) {
//		this.id = id;
//	}
//
//	/**
//	 * Get the 主键.
//	 * 
//	 * @return 主键
//	 */
//	public String getId() {
//		return this.id;
//	}

	/**
	 * Set the 商户订单号.
	 * 
	 * @param outTradeNo
	 *            商户订单号
	 */
	public void setOutTradeNo(String outTradeNo) {
		this.outTradeNo = outTradeNo;
	}

	/**
	 * Get the 商户订单号.
	 * 
	 * @return 商户订单号
	 */
	public String getOutTradeNo() {
		return this.outTradeNo;
	}

	/**
	 * Set the 订单总金额(分).
	 * 
	 * @param totalPrice
	 *            订单总金额(分)
	 */
	public void setTotalPrice(Integer totalPrice) {
		this.totalPrice = totalPrice;
	}

	/**
	 * Get the 订单总金额(分).
	 * 
	 * @return 订单总金额(分)
	 */
	public Integer getTotalPrice() {
		return this.totalPrice;
	}

	/**
	 * Set the 订单总运费(分).
	 * 
	 * @param totalFare
	 *            订单总运费(分)
	 */
	public void setTotalFare(Integer totalFare) {
		this.totalFare = totalFare;
	}

	/**
	 * Get the 订单总运费(分).
	 * 
	 * @return 订单总运费(分)
	 */
	public Integer getTotalFare() {
		return this.totalFare;
	}

	/**
	 * Set the 实付金额(分).
	 * 
	 * @param payPrice
	 *            实付金额(分)
	 */
	public void setPayPrice(Integer payPrice) {
		this.payPrice = payPrice;
	}

	/**
	 * Get the 实付金额(分).
	 * 
	 * @return 实付金额(分)
	 */
	public Integer getPayPrice() {
		return this.payPrice;
	}

	/**
	 * Set the 使用总积分.
	 * 
	 * @param totalPoints
	 *            使用总积分
	 */
	public void setTotalPoints(Integer totalPoints) {
		this.totalPoints = totalPoints;
	}

	/**
	 * Get the 使用总积分.
	 * 
	 * @return 使用总积分
	 */
	public Integer getTotalPoints() {
		return this.totalPoints;
	}

	/**
	 * Set the 提交时间.
	 * 
	 * @param commitTime
	 *            提交时间
	 */
	public void setCommitTime(Long commitTime) {
		this.commitTime = commitTime;
	}

	/**
	 * Get the 提交时间.
	 * 
	 * @return 提交时间
	 */
	public Long getCommitTime() {
		return this.commitTime;
	}

	/**
	 * Set the 用户id.
	 * 
	 * @param userId
	 *            用户id
	 */
	public void setUserId(String userId) {
		this.userId = userId;
	}

	/**
	 * Get the 用户id.
	 * 
	 * @return 用户id
	 */
	public String getUserId() {
		return this.userId;
	}

	/**
	 * Set the 渠道id.
	 * 
	 * @param channelId
	 *            渠道id
	 */
	public void setChannelId(String channelId) {
		this.channelId = channelId;
	}

	/**
	 * Get the 渠道id.
	 * 
	 * @return 渠道id
	 */
	public String getChannelId() {
		return this.channelId;
	}

	/**
	 * Set the 订单内容校验码(针对订单支付金额，随机数，支付方式，系统支付编码进行md5加密).
	 * 
	 * @param contentMd5
	 *            订单内容校验码(针对订单支付金额，随机数，支付方式，系统支付编码进行md5加密)
	 */
	public void setContentMd5(String contentMd5) {
		this.contentMd5 = contentMd5;
	}

	/**
	 * Get the 订单内容校验码(针对订单支付金额，随机数，支付方式，系统支付编码进行md5加密).
	 * 
	 * @return 订单内容校验码(针对订单支付金额，随机数，支付方式，系统支付编码进行md5加密)
	 */
	public String getContentMd5() {
		return this.contentMd5;
	}

	/**
	 * Set the 支付方式:默认0-无 1-微信 2-支付宝 3-银联.
	 * 
	 * @param payWay
	 *            支付方式:默认0-无 1-微信 2-支付宝 3-银联
	 */
	public void setPayWay(String payWay) {
		this.payWay = payWay;
	}

	/**
	 * Get the 支付方式:默认0-无 1-微信 2-支付宝 3-银联.
	 * 
	 * @return 支付方式:默认0-无 1-微信 2-支付宝 3-银联
	 */
	public String getPayWay() {
		return this.payWay;
	}

	/**
	 * Set the 支付类型.
	 * 
	 * @param payType
	 *            支付类型
	 */
	public void setPayType(String payType) {
		this.payType = payType;
	}

	/**
	 * Get the 支付类型.
	 * 
	 * @return 支付类型
	 */
	public String getPayType() {
		return this.payType;
	}

	/**
	 * Set the 支付状态（默认-0，成功-1，失败-2，3-异常）.
	 * 
	 * @param payStatus
	 *            支付状态（默认-0，成功-1，失败-2，3-异常）
	 */
	public void setPayStatus(String payStatus) {
		this.payStatus = payStatus;
	}

	/**
	 * Get the 支付状态（默认-0，成功-1，失败-2，3-异常）.
	 * 
	 * @return 支付状态（默认-0，成功-1，失败-2，3-异常）
	 */
	public String getPayStatus() {
		return this.payStatus;
	}

	/**
	 * Set the 返回状态码.
	 * 
	 * @param returnCode
	 *            返回状态码
	 */
	public void setReturnCode(String returnCode) {
		this.returnCode = returnCode;
	}

	/**
	 * Get the 返回状态码.
	 * 
	 * @return 返回状态码
	 */
	public String getReturnCode() {
		return this.returnCode;
	}

	/**
	 * Set the 返回信息.
	 * 
	 * @param returnMsg
	 *            返回信息
	 */
	public void setReturnMsg(String returnMsg) {
		this.returnMsg = returnMsg;
	}

	/**
	 * Get the 返回信息.
	 * 
	 * @return 返回信息
	 */
	public String getReturnMsg() {
		return this.returnMsg;
	}

	/**
	 * Set the 业务结果.
	 * 
	 * @param resultCode
	 *            业务结果
	 */
	public void setResultCode(String resultCode) {
		this.resultCode = resultCode;
	}

	/**
	 * Get the 业务结果.
	 * 
	 * @return 业务结果
	 */
	public String getResultCode() {
		return this.resultCode;
	}

	/**
	 * Set the 错误代码.
	 * 
	 * @param errCode
	 *            错误代码
	 */
	public void setErrCode(String errCode) {
		this.errCode = errCode;
	}

	/**
	 * Get the 错误代码.
	 * 
	 * @return 错误代码
	 */
	public String getErrCode() {
		return this.errCode;
	}

	/**
	 * Set the 错误代码描述.
	 * 
	 * @param errCodeDes
	 *            错误代码描述
	 */
	public void setErrCodeDes(String errCodeDes) {
		this.errCodeDes = errCodeDes;
	}

	/**
	 * Get the 错误代码描述.
	 * 
	 * @return 错误代码描述
	 */
	public String getErrCodeDes() {
		return this.errCodeDes;
	}

	/**
	 * Set the 商品名称.
	 * 
	 * @param subject
	 *            商品名称
	 */
	public void setSubject(String subject) {
		this.subject = subject;
	}

	/**
	 * Get the 商品名称.
	 * 
	 * @return 商品名称
	 */
	public String getSubject() {
		return this.subject;
	}

	/**
	 * Set the 商品描述.
	 * 
	 * @param body
	 *            商品描述
	 */
	public void setBody(String body) {
		this.body = body;
	}

	/**
	 * Get the 商品描述.
	 * 
	 * @return 商品描述
	 */
	public String getBody() {
		return this.body;
	}

	/**
	 * Set the 商品详情.
	 * 
	 * @param detail
	 *            商品详情
	 */
	public void setDetail(String detail) {
		this.detail = detail;
	}

	/**
	 * Get the 商品详情.
	 * 
	 * @return 商品详情
	 */
	public String getDetail() {
		return this.detail;
	}

	/**
	 * Set the 前台同步通知状态.
	 * 
	 * @param frontNotifyStatus
	 *            前台同步通知状态
	 */
	public void setFrontNotifyStatus(String frontNotifyStatus) {
		this.frontNotifyStatus = frontNotifyStatus;
	}

	/**
	 * Get the 前台同步通知状态.
	 * 
	 * @return 前台同步通知状态
	 */
	public String getFrontNotifyStatus() {
		return this.frontNotifyStatus;
	}

	/**
	 * Set the 卖家帐号（卖家在支付平台注册的号）.
	 * 
	 * @param sellerNum
	 *            卖家帐号（卖家在支付平台注册的号）
	 */
	public void setSellerNum(String sellerNum) {
		this.sellerNum = sellerNum;
	}

	/**
	 * Get the 卖家帐号（卖家在支付平台注册的号）.
	 * 
	 * @return 卖家帐号（卖家在支付平台注册的号）
	 */
	public String getSellerNum() {
		return this.sellerNum;
	}

	/**
	 * Set the 卖家帐户号（支付平台分配给卖家的号）.
	 * 
	 * @param sellerId
	 *            卖家帐户号（支付平台分配给卖家的号）
	 */
	public void setSellerId(String sellerId) {
		this.sellerId = sellerId;
	}

	/**
	 * Get the 卖家帐户号（支付平台分配给卖家的号）.
	 * 
	 * @return 卖家帐户号（支付平台分配给卖家的号）
	 */
	public String getSellerId() {
		return this.sellerId;
	}

	/**
	 * Set the 买家账户号（支付平台分配给买家的身份标志）.
	 * 
	 * @param buyerId
	 *            买家账户号（支付平台分配给买家的身份标志）
	 */
	public void setBuyerId(String buyerId) {
		this.buyerId = buyerId;
	}

	/**
	 * Get the 买家账户号（支付平台分配给买家的身份标志）.
	 * 
	 * @return 买家账户号（支付平台分配给买家的身份标志）
	 */
	public String getBuyerId() {
		return this.buyerId;
	}

	/**
	 * Set the 买家支付银行帐号.
	 * 
	 * @param bankNo
	 *            买家支付银行帐号
	 */
	public void setBankNo(String bankNo) {
		this.bankNo = bankNo;
	}

	/**
	 * Get the 买家支付银行帐号.
	 * 
	 * @return 买家支付银行帐号
	 */
	public String getBankNo() {
		return this.bankNo;
	}

	/**
	 * Set the 设备号.
	 * 
	 * @param deviceInfo
	 *            设备号
	 */
	public void setDeviceInfo(String deviceInfo) {
		this.deviceInfo = deviceInfo;
	}

	/**
	 * Get the 设备号.
	 * 
	 * @return 设备号
	 */
	public String getDeviceInfo() {
		return this.deviceInfo;
	}

	/**
	 * Set the 参数编码字符集.
	 * 
	 * @param charset
	 *            参数编码字符集
	 */
	public void setCharset(String charset) {
		this.charset = charset;
	}

	/**
	 * Get the 参数编码字符集.
	 * 
	 * @return 参数编码字符集
	 */
	public String getCharset() {
		return this.charset;
	}

	/**
	 * Set the 签名方式.
	 * 
	 * @param signType
	 *            签名方式
	 */
	public void setSignType(String signType) {
		this.signType = signType;
	}

	/**
	 * Get the 签名方式.
	 * 
	 * @return 签名方式
	 */
	public String getSignType() {
		return this.signType;
	}

	/**
	 * Set the 签名.
	 * 
	 * @param sign
	 *            签名
	 */
	public void setSign(String sign) {
		this.sign = sign;
	}

	/**
	 * Get the 签名.
	 * 
	 * @return 签名
	 */
	public String getSign() {
		return this.sign;
	}

	/**
	 * Set the 附加数据.
	 * 
	 * @param attch
	 *            附加数据
	 */
	public void setAttch(String attch) {
		this.attch = attch;
	}

	/**
	 * Get the 附加数据.
	 * 
	 * @return 附加数据
	 */
	public String getAttch() {
		return this.attch;
	}

	/**
	 * Set the 交易类型.
	 * 
	 * @param tradeType
	 *            交易类型
	 */
	public void setTradeType(String tradeType) {
		this.tradeType = tradeType;
	}

	/**
	 * Get the 交易类型.
	 * 
	 * @return 交易类型
	 */
	public String getTradeType() {
		return this.tradeType;
	}

	/**
	 * Set the 交易状态.
	 * 
	 * @param tradeStatus
	 *            交易状态
	 */
	public void setTradeStatus(String tradeStatus) {
		this.tradeStatus = tradeStatus;
	}

	/**
	 * Get the 交易状态.
	 * 
	 * @return 交易状态
	 */
	public String getTradeStatus() {
		return this.tradeStatus;
	}

	/**
	 * Set the 预支付交易会话标识.
	 * 
	 * @param prepayId
	 *            预支付交易会话标识
	 */
	public void setPrepayId(String prepayId) {
		this.prepayId = prepayId;
	}

	/**
	 * Get the 预支付交易会话标识.
	 * 
	 * @return 预支付交易会话标识
	 */
	public String getPrepayId() {
		return this.prepayId;
	}

	/**
	 * Set the 通知时间.
	 * 
	 * @param notifyTime
	 *            通知时间
	 */
	public void setNotifyTime(Long notifyTime) {
		this.notifyTime = notifyTime;
	}

	/**
	 * Get the 通知时间.
	 * 
	 * @return 通知时间
	 */
	public Long getNotifyTime() {
		return this.notifyTime;
	}

	/**
	 * Set the 通知类型.
	 * 
	 * @param notifyType
	 *            通知类型
	 */
	public void setNotifyType(String notifyType) {
		this.notifyType = notifyType;
	}

	/**
	 * Get the 通知类型.
	 * 
	 * @return 通知类型
	 */
	public String getNotifyType() {
		return this.notifyType;
	}

	/**
	 * Set the 通知校验ID.
	 * 
	 * @param notifyId
	 *            通知校验ID
	 */
	public void setNotifyId(String notifyId) {
		this.notifyId = notifyId;
	}

	/**
	 * Get the 通知校验ID.
	 * 
	 * @return 通知校验ID
	 */
	public String getNotifyId() {
		return this.notifyId;
	}

	/**
	 * Set the 交易流水号.
	 * 
	 * @param tradeNo
	 *            交易流水号
	 */
	public void setTradeNo(String tradeNo) {
		this.tradeNo = tradeNo;
	}

	/**
	 * Get the 交易流水号.
	 * 
	 * @return 交易流水号
	 */
	public String getTradeNo() {
		return this.tradeNo;
	}

	/**
	 * Set the 交易创建时间.
	 * 
	 * @param gmtCreate
	 *            交易创建时间
	 */
	public void setGmtCreate(Long gmtCreate) {
		this.gmtCreate = gmtCreate;
	}

	/**
	 * Get the 交易创建时间.
	 * 
	 * @return 交易创建时间
	 */
	public Long getGmtCreate() {
		return this.gmtCreate;
	}

	/**
	 * Set the 交易付款时间.
	 * 
	 * @param gmtPayment
	 *            交易付款时间
	 */
	public void setGmtPayment(Long gmtPayment) {
		this.gmtPayment = gmtPayment;
	}

	/**
	 * Get the 交易付款时间.
	 * 
	 * @return 交易付款时间
	 */
	public Long getGmtPayment() {
		return this.gmtPayment;
	}

	/**
	 * Set the 交易关闭时间.
	 * 
	 * @param gmtClose
	 *            交易关闭时间
	 */
	public void setGmtClose(Long gmtClose) {
		this.gmtClose = gmtClose;
	}

	/**
	 * Get the 交易关闭时间.
	 * 
	 * @return 交易关闭时间
	 */
	public Long getGmtClose() {
		return this.gmtClose;
	}

	/**
	 * Set the 扩展字段.
	 * 
	 * @param ext
	 *            扩展字段
	 */
	public void setExt(String ext) {
		this.ext = ext;
	}

	/**
	 * Get the 扩展字段.
	 * 
	 * @return 扩展字段
	 */
	public String getExt() {
		return this.ext;
	}

	public String getBusinessId() {
		return businessId;
	}

	public void setBusinessId(String businessId) {
		this.businessId = businessId;
	}

	@Override
	public String toString() {
		return "PayInfo [outTradeNo=" + outTradeNo + ", totalPrice=" + totalPrice + ", totalFare=" + totalFare
				+ ", payPrice=" + payPrice + ", totalPoints=" + totalPoints + ", commitTime=" + commitTime + ", userId="
				+ userId + ", channelId=" + channelId + ", contentMd5=" + contentMd5 + ", payWay=" + payWay
				+ ", payType=" + payType + ", payStatus=" + payStatus + ", returnCode=" + returnCode + ", returnMsg="
				+ returnMsg + ", resultCode=" + resultCode + ", errCode=" + errCode + ", errCodeDes=" + errCodeDes
				+ ", subject=" + subject + ", body=" + body + ", detail=" + detail + ", frontNotifyStatus="
				+ frontNotifyStatus + ", sellerNum=" + sellerNum + ", sellerId=" + sellerId + ", buyerId=" + buyerId
				+ ", bankNo=" + bankNo + ", deviceInfo=" + deviceInfo + ", charset=" + charset + ", signType="
				+ signType + ", sign=" + sign + ", attch=" + attch + ", tradeType=" + tradeType + ", tradeStatus="
				+ tradeStatus + ", prepayId=" + prepayId + ", notifyTime=" + notifyTime + ", notifyType=" + notifyType
				+ ", notifyId=" + notifyId + ", tradeNo=" + tradeNo + ", gmtCreate=" + gmtCreate + ", gmtPayment="
				+ gmtPayment + ", gmtClose=" + gmtClose + ", ext=" + ext + ", businessId=" + businessId + "]";
	}

	
}