package com.zyhao.openec.order.entity;

import java.io.Serializable;

import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.validation.constraints.NotNull;

import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedDate;


/**
 * Model class of 订单表.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */

@Entity(name="refund_orders")
@SequenceGenerator(name="SEQ_refund_orders_id",sequenceName="SEQ_refund_orders_id")
public class RefundOrders implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** id. */

	@Id
	@GeneratedValue(strategy=GenerationType.SEQUENCE,generator="SEQ_refund_orders_id")
	private Long id;

	/** 退单号. */
	private String refundOrderCode;

	/** 订单号 . */
	private String orderCode;

	/*退单类型--退款(0)/退货(1)*/
	private String type;

	/** 退单状态. */
	private String status;

	/** 订单提交时间. */
	@CreatedDate
	private Long createAt;

	/** 最后变更时间. */
	@LastModifiedDate
	private Long modifyAt;

	/** 商户名称. */
	private String sellerName;

	/** 商户id. */
	private Long sellerId;

	/** 渠道. */
	private String channelId;

	/** 用户. */
	private String memberId;

	/** 商品件数. */
	private Long goodsCount;

	/** 退单金额(分). */
	private Integer realSellPrice;

	/** 物流信息(JSON). */
	private String logistics;

	/** 商户订单号. */
	private String outTradeNo;

	/** 退款原因. */
	private String refundReason;

	/** 审核意见. */
	private String refundOpinion;

	/** 是否出账单. */
	private String isBilled;
	
	@NotNull
	@OneToMany(cascade = { CascadeType.PERSIST, CascadeType.REFRESH,  
            CascadeType.REMOVE }, fetch = FetchType.LAZY)
	@JoinColumn(name="refundOrderId",referencedColumnName ="refundOrderCode")
	private List<RefundOrderItem> refundOrderItems;
	
	public List<RefundOrderItem> getRefundOrderItems() {
		return refundOrderItems;
	}

	public void setRefundOrderItems(List<RefundOrderItem> refundOrderItems) {
		this.refundOrderItems = refundOrderItems;
	}

	/**
	 * Constructor.
	 */
	public RefundOrders() {
	}

	/**
	 * Set the id.
	 * 
	 * @param id
	 *            id
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * Get the id.
	 * 
	 * @return id
	 */
	public Long getId() {
		return this.id;
	}

	/**
	 * Set the 退单号.
	 * 
	 * @param refundOrderCode
	 *            退单号
	 */
	public void setRefundOrderCode(String refundOrderCode) {
		this.refundOrderCode = refundOrderCode;
	}

	/**
	 * Get the 退单号.
	 * 
	 * @return 退单号
	 */
	public String getRefundOrderCode() {
		return this.refundOrderCode;
	}

	/**
	 * Set the 订单号 .
	 * 
	 * @param orderCode
	 *            订单号 
	 */
	public void setOrderCode(String orderCode) {
		this.orderCode = orderCode;
	}

	/**
	 * Get the 订单号 .
	 * 
	 * @return 订单号 
	 */
	public String getOrderCode() {
		return this.orderCode;
	}

	/**
	 * Set the 订单状态.
	 * 
	 * @param status
	 *            订单状态
	 */
	public void setStatus(String status) {
		this.status = status;
	}

	/**
	 * Get the 订单状态.
	 * 
	 * @return 订单状态
	 */
	public String getStatus() {
		return this.status;
	}

	/**
	 * Set the 订单提交时间.
	 * 
	 * @param createAt
	 *            订单提交时间
	 */
	public void setCreateAt(Long createAt) {
		this.createAt = createAt;
	}

	/**
	 * Get the 订单提交时间.
	 * 
	 * @return 订单提交时间
	 */
	public Long getCreateAt() {
		return this.createAt;
	}

	/**
	 * Set the 最后变更时间.
	 * 
	 * @param modifyAt
	 *            最后变更时间
	 */
	public void setModifyAt(Long modifyAt) {
		this.modifyAt = modifyAt;
	}

	/**
	 * Get the 最后变更时间.
	 * 
	 * @return 最后变更时间
	 */
	public Long getModifyAt() {
		return this.modifyAt;
	}

	/**
	 * Set the 商户名称.
	 * 
	 * @param sellerName
	 *            商户名称
	 */
	public void setSellerName(String sellerName) {
		this.sellerName = sellerName;
	}

	/**
	 * Get the 商户名称.
	 * 
	 * @return 商户名称
	 */
	public String getSellerName() {
		return this.sellerName;
	}

	/**
	 * Set the 商户id.
	 * 
	 * @param sellerId
	 *            商户id
	 */
	public void setSellerId(Long sellerId) {
		this.sellerId = sellerId;
	}

	/**
	 * Get the 商户id.
	 * 
	 * @return 商户id
	 */
	public Long getSellerId() {
		return this.sellerId;
	}

	/**
	 * Set the 渠道.
	 * 
	 * @param channelId
	 *            渠道
	 */
	public void setChannelId(String channelId) {
		this.channelId = channelId;
	}

	/**
	 * Get the 渠道.
	 * 
	 * @return 渠道
	 */
	public String getChannelId() {
		return this.channelId;
	}

	/**
	 * Set the 用户.
	 * 
	 * @param memberId
	 *            用户
	 */
	public void setMemberId(String memberId) {
		this.memberId = memberId;
	}

	/**
	 * Get the 用户.
	 * 
	 * @return 用户
	 */
	public String getMemberId() {
		return this.memberId;
	}

	/**
	 * Set the 商品件数.
	 * 
	 * @param goodsCount
	 *            商品件数
	 */
	public void setGoodsCount(Long goodsCount) {
		this.goodsCount = goodsCount;
	}

	/**
	 * Get the 商品件数.
	 * 
	 * @return 商品件数
	 */
	public Long getGoodsCount() {
		return this.goodsCount;
	}

	/**
	 * Set the 订单金额(分).
	 * 
	 * @param realSellPrice
	 *            订单金额(分)
	 */
	public void setRealSellPrice(Integer realSellPrice) {
		this.realSellPrice = realSellPrice;
	}

	/**
	 * Get the 订单金额(分).
	 * 
	 * @return 订单金额(分)
	 */
	public Integer getRealSellPrice() {
		return this.realSellPrice;
	}

	/**
	 * Set the 商户订单号.
	 * 
	 * @param outTradeNo
	 *            商户订单号
	 */
	public void setOutTradeNo(String outTradeNo) {
		this.outTradeNo = outTradeNo;
	}

	/**
	 * Get the 商户订单号.
	 * 
	 * @return 商户订单号
	 */
	public String getOutTradeNo() {
		return this.outTradeNo;
	}

	/**
	 * Set the 退款原因.
	 * 
	 * @param refundReason
	 *            退款原因
	 */
	public void setRefundReason(String refundReason) {
		this.refundReason = refundReason;
	}

	/**
	 * Get the 退款原因.
	 * 
	 * @return 退款原因
	 */
	public String getRefundReason() {
		return this.refundReason;
	}

	/**
	 * Set the 审核意见.
	 * 
	 * @param refundOpinion
	 *            审核意见
	 */
	public void setRefundOpinion(String refundOpinion) {
		this.refundOpinion = refundOpinion;
	}

	/**
	 * Get the 审核意见.
	 * 
	 * @return 审核意见
	 */
	public String getRefundOpinion() {
		return this.refundOpinion;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		RefundOrders other = (RefundOrders) obj;
		if (id == null) {
			if (other.id != null) {
				return false;
			}
		} else if (!id.equals(other.id)) {
			return false;
		}
		return true;
	}

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getLogistics() {
		return logistics;
	}

	public void setLogistics(String logistics) {
		this.logistics = logistics;
	}

	public String getIsBilled() {
		return isBilled;
	}

	public void setIsBilled(String isBilled) {
		this.isBilled = isBilled;
	}

	@Override
	public String toString() {
		return "RefundOrders [id=" + id + ", refundOrderCode=" + refundOrderCode + ", orderCode=" + orderCode
				+ ", type=" + type + ", status=" + status + ", createAt=" + createAt + ", modifyAt=" + modifyAt
				+ ", sellerName=" + sellerName + ", sellerId=" + sellerId + ", channelId=" + channelId + ", memberId="
				+ memberId + ", goodsCount=" + goodsCount + ", realSellPrice=" + realSellPrice + ", logistics="
				+ logistics + ", outTradeNo=" + outTradeNo + ", refundReason=" + refundReason + ", refundOpinion="
				+ refundOpinion + ", isBilled=" + isBilled + ", refundOrderItems=" + refundOrderItems + "]";
	}



}
